### ISSUE TITLE
installation problem : fspy file not showing in the add-ons folder

### ISSUE THREAD

**Issue by lucafonty** [stuffmatic/fSpy#26]
Hi everybody !

I am using a mac. 

When i try to install Fspy, i correctly import the source code and then when i want to tick it in the add-on menu I don't find it anywhere. I tried to download it several other times
<img width="944" alt="Capture d’écran 2019-10-08 à 01 35 28" 
 and it won't show up...

If anybody has some idea of what is happening it would be amazing

src="https://user-images.githubusercontent.com/24400032/66356637-f3a59b80-e96b-11e9-9fe6-20d02825f636.png">
Thxxxxx

**Comment by stuffmatic** [comment]
Make sure to install the zip file. See _Important note for mac users_ here https://github.com/stuffmatic/fSpy-Blender#getting-started

**Comment by lucafonty** [comment]
I did it correctly following the advices...
My zip file is still zipped :-(

**Comment by MBing** [comment]
@lucafonty did you check if you have the correct zip file? This is the repo with the software installer. For mac -> `.dmg`. You will need both the software and the add on if you want to work with Blender.

The link Stuffmatic provided is for the actual add-on. So that might be the reason why it doesn't work to import the add on, as it doesn't recognise an add-on or a zip file.
You can download the latest release zip of the add on for Blender here: 
https://github.com/stuffmatic/fSpy-Blender/releases

Make sure to select:
<img width="811" alt="Screenshot 2019-12-20 at 16 06 47" src="https://user-images.githubusercontent.com/2140223/71263725-c77ea180-2342-11ea-9f23-b00e93afef5d.png">
as the other zip files are only the source code.

Hope this helps and have fun!

**Comment by Andy-bee** [comment]
I have been trying to install the fspy addon on blender. I am on windows hence have tryed downloading both the zip file from the official site and the second extension file for windows and followed the official instruction given on the site but whenever I get to blender to install the addon it gives me no menu to check on and whenever I try to open the application it gives a notification that, the node.dll cannot be found. please any help for me?

**Comment by stuffmatic** [comment]
If you're still having problems with this, please open an issue in the importer issue tracker https://github.com/stuffmatic/fSpy-Blender/issues
